/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonld as UserApiJsonld } from '../../models/User/api-jsonld';

export interface ApiUsersIdGet$Params {

/**
 * User identifier
 */
  id: string;
}

export function apiUsersIdGet(http: HttpClient, rootUrl: string, params: ApiUsersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiJsonld>> {
  const rb = new RequestBuilder(rootUrl, apiUsersIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserApiJsonld>;
    })
  );
}

apiUsersIdGet.PATH = '/api/users/{id}';
