/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiPatch as UserUserApiPatch } from '../../models/User-user/api-patch';
import { ApiJsonld as UserApiJsonld } from '../../models/User/api-jsonld';

export interface ApiUsersIdPatch$Params {

/**
 * User identifier
 */
  id: string;
  
    /**
     * The updated User resource
     */
    body: UserUserApiPatch
}

export function apiUsersIdPatch(http: HttpClient, rootUrl: string, params: ApiUsersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiJsonld>> {
  const rb = new RequestBuilder(rootUrl, apiUsersIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
    rb.body(params.body, 'application/merge-patch+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserApiJsonld>;
    })
  );
}

apiUsersIdPatch.PATH = '/api/users/{id}';
