# Organization and project keys are displayed in the right sidebar of the project homepage
sonar.organization=mochadocs
sonar.projectKey=mochadocs_partnerportal
sonar.projectName=partner-portal
sonar.host.url=https://sonarcloud.io
sonar.token=32148a3640eedc91d3696753a5addfb032c084b9

# Source code location
sonar.sources=server/src, client/src
sonar.tests=server/tests

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Exclude directories
sonar.exclusions=var/**, vendor/**, public/bundles/**, public/build/**, src/Kernel.php, server/src/DataFixtures/**


# PHP specific configuration
#sonar.php.coverage.reportPaths=var/coverage/clover.xml
#sonar.php.tests.reportPath=var/coverage/junit.xml

# Language
sonar.language=php
