/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface LoginCheckPost$Params {
  
    /**
     * The login data
     */
    body: {
'email': string;
'password': string;
}
}

export function loginCheckPost(http: HttpClient, rootUrl: string, params: LoginCheckPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'token': string;
}>> {
  const rb = new RequestBuilder(rootUrl, loginCheckPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'token': string;
      }>;
    })
  );
}

loginCheckPost.PATH = '/auth';
