/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ModuleWithProviders, NgModule, Optional, SkipSelf } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ApiAffiliatePartnerService } from './services/api-affiliate-partner.service';
import { ApiPartnerService } from './services/api-partner.service';
import { ApiClientService } from './services/api-client.service';
import { ApiGrowthPartnerService } from './services/api-growth-partner.service';
import { ApiLoginCheckService } from './services/api-login-check.service';
import { ApiSolutionPartnerService } from './services/api-solution-partner.service';
import { ApiSolutionProviderService } from './services/api-solution-provider.service';
import { ApiUserService } from './services/api-user.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ApiAffiliatePartnerService,
    ApiPartnerService,
    ApiClientService,
    ApiGrowthPartnerService,
    ApiLoginCheckService,
    ApiSolutionPartnerService,
    ApiSolutionProviderService,
    ApiUserService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
