/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiAffiliatePartnerPatch } from './models/api-affiliate-partner-patch';
export type { ApiJsonldPost as AffiliatePartnerApiJsonldPost } from './models/AffiliatePartner/api-jsonld-post';
export type { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from './models/AffiliatePartner/api-jsonld-read';
export type { ApiPatch as ClientClientApiPatch } from './models/Client-client/api-patch';
export type { ApiAssignPartner as ClientClientPatchApiAssignPartner } from './models/Client-client/patch/api-assign-partner';
export type { ApiPost as ClientJsonldClientApiPost } from './models/Client/jsonld-client/api-post';
export type { ApiRead as ClientJsonldClientApiRead } from './models/Client/jsonld-client/api-read';
export type { ApiJsonldRead as ClientApiJsonldRead } from './models/Client/api-jsonld-read';
export type { ApiGrowthPartnerPatch } from './models/api-growth-partner-patch';
export type { ApiJsonldPost as GrowthPartnerApiJsonldPost } from './models/GrowthPartner/api-jsonld-post';
export type { ApiJsonldRead as GrowthPartnerApiJsonldRead } from './models/GrowthPartner/api-jsonld-read';
export type { ApiPartner } from './models/api-partner';
export type { ApiJsonld as PartnerApiJsonld } from './models/Partner/api-jsonld';
export type { ApiRead as PartnerJsonldClientApiRead } from './models/Partner/jsonld-client/api-read';
export type { ApiSolutionPartnerPatch } from './models/api-solution-partner-patch';
export type { ApiJsonldPost as SolutionPartnerApiJsonldPost } from './models/SolutionPartner/api-jsonld-post';
export type { ApiJsonldRead as SolutionPartnerApiJsonldRead } from './models/SolutionPartner/api-jsonld-read';
export type { ApiSolutionProviderPatch } from './models/api-solution-provider-patch';
export type { ApiJsonldPost as SolutionProviderApiJsonldPost } from './models/SolutionProvider/api-jsonld-post';
export type { ApiJsonldRead as SolutionProviderApiJsonldRead } from './models/SolutionProvider/api-jsonld-read';
export type { ApiPatch as UserUserApiPatch } from './models/User-user/api-patch';
export type { ApiJsonld as UserApiJsonld } from './models/User/api-jsonld';
export type { ApiJsonldRead as UserApiJsonldRead } from './models/User/api-jsonld-read';
export type { ApiPost as UserJsonldUserApiPost } from './models/User/jsonld-user/api-post';
