/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiAffiliatePartnerService } from './services/api-affiliate-partner.service';
export { ApiPartnerService } from './services/api-partner.service';
export { ApiClientService } from './services/api-client.service';
export { ApiGrowthPartnerService } from './services/api-growth-partner.service';
export { ApiLoginCheckService } from './services/api-login-check.service';
export { ApiSolutionPartnerService } from './services/api-solution-partner.service';
export { ApiSolutionProviderService } from './services/api-solution-provider.service';
export { ApiUserService } from './services/api-user.service';
