/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldPost as GrowthPartnerApiJsonldPost } from '../../models/GrowthPartner/api-jsonld-post';
import { ApiJsonldRead as GrowthPartnerApiJsonldRead } from '../../models/GrowthPartner/api-jsonld-read';

export interface ApiGrowthPartnersPost$Params {
  
    /**
     * The new GrowthPartner resource
     */
    body: GrowthPartnerApiJsonldPost
}

export function apiGrowthPartnersPost(http: HttpClient, rootUrl: string, params: ApiGrowthPartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<GrowthPartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiGrowthPartnersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/ld+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GrowthPartnerApiJsonldRead>;
    })
  );
}

apiGrowthPartnersPost.PATH = '/api/growth_partners';
