/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiGrowthPartnerPatch } from '../../models/api-growth-partner-patch';
import { ApiJsonldRead as GrowthPartnerApiJsonldRead } from '../../models/GrowthPartner/api-jsonld-read';

export interface ApiGrowthPartnersIdPatch$Params {

/**
 * GrowthPartner identifier
 */
  id: string;
  
    /**
     * The updated GrowthPartner resource
     */
    body: ApiGrowthPartnerPatch
}

export function apiGrowthPartnersIdPatch(http: HttpClient, rootUrl: string, params: ApiGrowthPartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<GrowthPartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiGrowthPartnersIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
    rb.body(params.body, 'application/merge-patch+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GrowthPartnerApiJsonldRead>;
    })
  );
}

apiGrowthPartnersIdPatch.PATH = '/api/growth_partners/{id}';
