/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldRead as GrowthPartnerApiJsonldRead } from '../../models/GrowthPartner/api-jsonld-read';

export interface ApiGrowthPartnersGetCollection$Params {

/**
 * The collection page number
 */
  page?: number;
}

export function apiGrowthPartnersGetCollection(http: HttpClient, rootUrl: string, params?: ApiGrowthPartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
  const rb = new RequestBuilder(rootUrl, apiGrowthPartnersGetCollection.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {"style":"form","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'member': Array<GrowthPartnerApiJsonldRead>;
      'totalItems'?: number;
      'view'?: {
      '@id'?: string;
      '@type'?: string;
      'first'?: string;
      'last'?: string;
      'previous'?: string;
      'next'?: string;
      };
      'search'?: {
      '@type'?: string;
      'template'?: string;
      'variableRepresentation'?: string;
      'mapping'?: Array<{
      '@type'?: string;
      'variable'?: string;
      'property'?: string;
      'required'?: boolean;
      }>;
      };
      }>;
    })
  );
}

apiGrowthPartnersGetCollection.PATH = '/api/growth_partners';
