/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldRead as GrowthPartnerApiJsonldRead } from '../../models/GrowthPartner/api-jsonld-read';

export interface ApiGrowthPartnersIdGet$Params {

/**
 * GrowthPartner identifier
 */
  id: string;
}

export function apiGrowthPartnersIdGet(http: HttpClient, rootUrl: string, params: ApiGrowthPartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<GrowthPartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiGrowthPartnersIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GrowthPartnerApiJsonldRead>;
    })
  );
}

apiGrowthPartnersIdGet.PATH = '/api/growth_partners/{id}';
