/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from '../../models/AffiliatePartner/api-jsonld-read';
import { ApiJsonldRead as ClientApiJsonldRead } from '../../models/Client/api-jsonld-read';
import { ApiJsonldRead as SolutionPartnerApiJsonldRead } from '../../models/SolutionPartner/api-jsonld-read';
import { ApiJsonldRead as SolutionProviderApiJsonldRead } from '../../models/SolutionProvider/api-jsonld-read';
import { ApiJsonldRead as UserApiJsonldRead } from '../../models/User/api-jsonld-read';

export interface ApiJsonldRead {
  '@context'?: (string | {
'@vocab': string;
'hydra': 'http://www.w3.org/ns/hydra/core#';
[key: string]: any;
});
  '@id'?: string;
  '@type'?: string;
  affiliatePartners?: Array<AffiliatePartnerApiJsonldRead>;
  clients?: Array<ClientApiJsonldRead>;
  contactPerson?: string;
  email?: string;
  endDate?: string;
  id?: string;
  name?: string;
  solutionPartners?: Array<SolutionPartnerApiJsonldRead>;
  solutionProviders?: Array<SolutionProviderApiJsonldRead>;
  startDate?: string;
  users?: Array<UserApiJsonldRead>;
}
