/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiPost {
  email?: string;
  isActive?: boolean;
  name?: string;

  /**
   * a client can have a partner, but might not have one
   */
  partner?: string;
  startDate?: string;
}
