/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiRead as PartnerJsonldClientApiRead } from '../../../models/Partner/jsonld-client/api-read';

export interface ApiRead {
  '@context'?: (string | {
'@vocab': string;
'hydra': 'http://www.w3.org/ns/hydra/core#';
[key: string]: any;
});
  '@id'?: string;
  '@type'?: string;
  active?: boolean;
  email?: string;
  name?: string;

  /**
   * a client can have a partner, but might not have one
   */
  partner?: (PartnerJsonldClientApiRead | null);
  startDate?: string;
}
