/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiRead as ClientJsonldClientApiRead } from '../../models/Client/jsonld-client/api-read';

export interface ApiClientsIdGet$Params {

/**
 * Client identifier
 */
  id: string;
}

export function apiClientsIdGet(http: HttpClient, rootUrl: string, params: ApiClientsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
  const rb = new RequestBuilder(rootUrl, apiClientsIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientJsonldClientApiRead>;
    })
  );
}

apiClientsIdGet.PATH = '/api/clients/{id}';
