/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import {
  ApiAssignPartner as ClientClientPatchApiAssignPartner
} from '../../models/Client-client/patch/api-assign-partner';
import { ApiRead as ClientJsonldClientApiRead } from '../../models/Client/jsonld-client/api-read';

export interface ApiClientsIdregisteredPartnerPatch$Params {

/**
 * Client identifier
 */
  id: string;
  
    /**
     * The updated Client resource
     */
    body: ClientClientPatchApiAssignPartner
}

export function apiClientsIdregisteredPartnerPatch(http: HttpClient, rootUrl: string, params: ApiClientsIdregisteredPartnerPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
  const rb = new RequestBuilder(rootUrl, apiClientsIdregisteredPartnerPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
    rb.body(params.body, 'application/merge-patch+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientJsonldClientApiRead>;
    })
  );
}

apiClientsIdregisteredPartnerPatch.PATH = '/api/clients/{id}/registeredPartner';
