/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiPost as ClientJsonldClientApiPost } from '../../models/Client/jsonld-client/api-post';
import { ApiRead as ClientJsonldClientApiRead } from '../../models/Client/jsonld-client/api-read';

export interface ApiClientsPost$Params {
  
    /**
     * The new Client resource
     */
    body: ClientJsonldClientApiPost
}

export function apiClientsPost(http: HttpClient, rootUrl: string, params: ApiClientsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
  const rb = new RequestBuilder(rootUrl, apiClientsPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/ld+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientJsonldClientApiRead>;
    })
  );
}

apiClientsPost.PATH = '/api/clients';
