/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiAffiliatePartnerPatch } from '../../models/api-affiliate-partner-patch';
import { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from '../../models/AffiliatePartner/api-jsonld-read';

export interface ApiAffiliatePartnersIdPatch$Params {

/**
 * AffiliatePartner identifier
 */
  id: string;
  
    /**
     * The updated AffiliatePartner resource
     */
    body: ApiAffiliatePartnerPatch
}

export function apiAffiliatePartnersIdPatch(http: HttpClient, rootUrl: string, params: ApiAffiliatePartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<AffiliatePartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiAffiliatePartnersIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
    rb.body(params.body, 'application/merge-patch+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AffiliatePartnerApiJsonldRead>;
    })
  );
}

apiAffiliatePartnersIdPatch.PATH = '/api/affiliate_partners/{id}';
