/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from '../../models/AffiliatePartner/api-jsonld-read';

export interface ApiAffiliatePartnersIdGet$Params {

/**
 * AffiliatePartner identifier
 */
  id: string;
}

export function apiAffiliatePartnersIdGet(http: HttpClient, rootUrl: string, params: ApiAffiliatePartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AffiliatePartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiAffiliatePartnersIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AffiliatePartnerApiJsonldRead>;
    })
  );
}

apiAffiliatePartnersIdGet.PATH = '/api/affiliate_partners/{id}';
