/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldPost as AffiliatePartnerApiJsonldPost } from '../../models/AffiliatePartner/api-jsonld-post';
import { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from '../../models/AffiliatePartner/api-jsonld-read';

export interface ApiAffiliatePartnersPost$Params {
  
    /**
     * The new AffiliatePartner resource
     */
    body: AffiliatePartnerApiJsonldPost
}

export function apiAffiliatePartnersPost(http: HttpClient, rootUrl: string, params: ApiAffiliatePartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AffiliatePartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiAffiliatePartnersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/ld+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AffiliatePartnerApiJsonldRead>;
    })
  );
}

apiAffiliatePartnersPost.PATH = '/api/affiliate_partners';
