/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiJsonld {
  '@context'?: (string | {
'@vocab': string;
'hydra': 'http://www.w3.org/ns/hydra/core#';
[key: string]: any;
});
  '@id'?: string;
  '@type'?: string;
  active?: boolean;
  email?: string;
  id?: string;
  isActive?: boolean;
  lastLoggedIn?: string;
  name?: string;
  partner?: string;
  roles?: Array<string>;
  userIdentifier?: string;
}
