/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldPost as SolutionPartnerApiJsonldPost } from '../../models/SolutionPartner/api-jsonld-post';
import { ApiJsonldRead as SolutionPartnerApiJsonldRead } from '../../models/SolutionPartner/api-jsonld-read';

export interface ApiSolutionPartnersPost$Params {
  
    /**
     * The new SolutionPartner resource
     */
    body: SolutionPartnerApiJsonldPost
}

export function apiSolutionPartnersPost(http: HttpClient, rootUrl: string, params: ApiSolutionPartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionPartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiSolutionPartnersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/ld+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SolutionPartnerApiJsonldRead>;
    })
  );
}

apiSolutionPartnersPost.PATH = '/api/solution_partners';
