/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldRead as SolutionPartnerApiJsonldRead } from '../../models/SolutionPartner/api-jsonld-read';

export interface ApiSolutionPartnersIdGet$Params {

/**
 * SolutionPartner identifier
 */
  id: string;
}

export function apiSolutionPartnersIdGet(http: HttpClient, rootUrl: string, params: ApiSolutionPartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionPartnerApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiSolutionPartnersIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SolutionPartnerApiJsonldRead>;
    })
  );
}

apiSolutionPartnersIdGet.PATH = '/api/solution_partners/{id}';
