/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiAssignPartner {

  /**
   * a client can have a partner, but might not have one
   */
  partner?: string;
}
