/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonldPost as SolutionProviderApiJsonldPost } from '../../models/SolutionProvider/api-jsonld-post';
import { ApiJsonldRead as SolutionProviderApiJsonldRead } from '../../models/SolutionProvider/api-jsonld-read';

export interface ApiSolutionProvidersPost$Params {
  
    /**
     * The new SolutionProvider resource
     */
    body: SolutionProviderApiJsonldPost
}

export function apiSolutionProvidersPost(http: HttpClient, rootUrl: string, params: ApiSolutionProvidersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionProviderApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiSolutionProvidersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/ld+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SolutionProviderApiJsonldRead>;
    })
  );
}

apiSolutionProvidersPost.PATH = '/api/solution_providers';
