/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiSolutionProviderPatch } from '../../models/api-solution-provider-patch';
import { ApiJsonldRead as SolutionProviderApiJsonldRead } from '../../models/SolutionProvider/api-jsonld-read';

export interface ApiSolutionProvidersIdPatch$Params {

/**
 * SolutionProvider identifier
 */
  id: string;
  
    /**
     * The updated SolutionProvider resource
     */
    body: ApiSolutionProviderPatch
}

export function apiSolutionProvidersIdPatch(http: HttpClient, rootUrl: string, params: ApiSolutionProvidersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionProviderApiJsonldRead>> {
  const rb = new RequestBuilder(rootUrl, apiSolutionProvidersIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
    rb.body(params.body, 'application/merge-patch+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SolutionProviderApiJsonldRead>;
    })
  );
}

apiSolutionProvidersIdPatch.PATH = '/api/solution_providers/{id}';
