/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiAffiliatePartnerPatch } from '../models/api-affiliate-partner-patch';
import { ApiSolutionPartnerPatch } from '../models/api-solution-partner-patch';
import { ApiSolutionProviderPatch } from '../models/api-solution-provider-patch';

export interface ApiGrowthPartnerPatch {
  affiliatePartners?: Array<ApiAffiliatePartnerPatch>;
  contactPerson?: string;
  endDate?: string;
  name?: string;
  solutionPartners?: Array<ApiSolutionPartnerPatch>;
  solutionProviders?: Array<ApiSolutionProviderPatch>;
  startDate?: string;
}
