/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiPartner {
  clients?: Array<string>;
  email?: string;
  id?: string;
  name?: string;
  users?: Array<string>;
}
