/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiAffiliatePartnerPatch {
  contactPerson?: string;
  endDate?: string;
  name?: string;
  registeredPartner?: string;
  renewalInterval?: string;
  startDate?: string;
}
