/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiJsonldPost {
  contactPerson?: string;
  email?: string;
  endDate?: string;
  name?: string;
  registeredPartner?: string;
  renewalInterval?: string;
  startDate?: string;
}
