/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import {
  apiSolutionPartnersGetCollection,
  ApiSolutionPartnersGetCollection$Params
} from '../fn/solution-partner/api-solution-partners-get-collection';
import {
  apiSolutionPartnersIdGet,
  ApiSolutionPartnersIdGet$Params
} from '../fn/solution-partner/api-solution-partners-id-get';
import {
  apiSolutionPartnersIdPatch,
  ApiSolutionPartnersIdPatch$Params
} from '../fn/solution-partner/api-solution-partners-id-patch';
import {
  apiSolutionPartnersPost,
  ApiSolutionPartnersPost$Params
} from '../fn/solution-partner/api-solution-partners-post';
import {
  getSolutionPartnersByRegisteredPartner,
  GetSolutionPartnersByRegisteredPartner$Params
} from '../fn/solution-partner/get-solution-partners-by-registered-partner';
import { ApiJsonldRead as SolutionPartnerApiJsonldRead } from '../models/SolutionPartner/api-jsonld-read';

@Injectable({ providedIn: 'root' })
export class ApiSolutionPartnerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSolutionPartnersGetCollection()` */
  static readonly ApiSolutionPartnersGetCollectionPath = '/api/solution_partners';

  /**
   * Retrieves the collection of SolutionPartner resources.
   *
   * Retrieves the collection of SolutionPartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionPartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionPartnersGetCollection$Response(params?: ApiSolutionPartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiSolutionPartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of SolutionPartner resources.
   *
   * Retrieves the collection of SolutionPartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionPartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionPartnersGetCollection(params?: ApiSolutionPartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiSolutionPartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiSolutionPartnersPost()` */
  static readonly ApiSolutionPartnersPostPath = '/api/solution_partners';

  /**
   * Creates a SolutionPartner resource.
   *
   * Creates a SolutionPartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionPartnersPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiSolutionPartnersPost$Response(params: ApiSolutionPartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionPartnerApiJsonldRead>> {
    return apiSolutionPartnersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a SolutionPartner resource.
   *
   * Creates a SolutionPartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionPartnersPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiSolutionPartnersPost(params: ApiSolutionPartnersPost$Params, context?: HttpContext): Observable<SolutionPartnerApiJsonldRead> {
    return this.apiSolutionPartnersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<SolutionPartnerApiJsonldRead>): SolutionPartnerApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `getSolutionPartnersByRegisteredPartner()` */
  static readonly GetSolutionPartnersByRegisteredPartnerPath = '/api/solution_partners/by_registered_partner/{registeredPartnerId}';

  /**
   * Retrieves the collection of SolutionPartner resources.
   *
   * Retrieves the collection of SolutionPartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSolutionPartnersByRegisteredPartner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSolutionPartnersByRegisteredPartner$Response(params: GetSolutionPartnersByRegisteredPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return getSolutionPartnersByRegisteredPartner(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of SolutionPartner resources.
   *
   * Retrieves the collection of SolutionPartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSolutionPartnersByRegisteredPartner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSolutionPartnersByRegisteredPartner(params: GetSolutionPartnersByRegisteredPartner$Params, context?: HttpContext): Observable<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.getSolutionPartnersByRegisteredPartner$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiSolutionPartnersIdGet()` */
  static readonly ApiSolutionPartnersIdGetPath = '/api/solution_partners/{id}';

  /**
   * Retrieves a SolutionPartner resource.
   *
   * Retrieves a SolutionPartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionPartnersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionPartnersIdGet$Response(params: ApiSolutionPartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionPartnerApiJsonldRead>> {
    return apiSolutionPartnersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a SolutionPartner resource.
   *
   * Retrieves a SolutionPartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionPartnersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionPartnersIdGet(params: ApiSolutionPartnersIdGet$Params, context?: HttpContext): Observable<SolutionPartnerApiJsonldRead> {
    return this.apiSolutionPartnersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SolutionPartnerApiJsonldRead>): SolutionPartnerApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `apiSolutionPartnersIdPatch()` */
  static readonly ApiSolutionPartnersIdPatchPath = '/api/solution_partners/{id}';

  /**
   * Updates the SolutionPartner resource.
   *
   * Updates the SolutionPartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionPartnersIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiSolutionPartnersIdPatch$Response(params: ApiSolutionPartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionPartnerApiJsonldRead>> {
    return apiSolutionPartnersIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the SolutionPartner resource.
   *
   * Updates the SolutionPartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionPartnersIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiSolutionPartnersIdPatch(params: ApiSolutionPartnersIdPatch$Params, context?: HttpContext): Observable<SolutionPartnerApiJsonldRead> {
    return this.apiSolutionPartnersIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<SolutionPartnerApiJsonldRead>): SolutionPartnerApiJsonldRead => r.body)
    );
  }

}
