/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { loginCheckPost, LoginCheckPost$Params } from '../fn/login-check/login-check-post';

@Injectable({ providedIn: 'root' })
export class ApiLoginCheckService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `loginCheckPost()` */
  static readonly LoginCheckPostPath = '/auth';

  /**
   * Creates a user token.
   *
   * Creates a user token.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `loginCheckPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  loginCheckPost$Response(params: LoginCheckPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'token': string;
}>> {
    return loginCheckPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a user token.
   *
   * Creates a user token.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `loginCheckPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  loginCheckPost(params: LoginCheckPost$Params, context?: HttpContext): Observable<{
'token': string;
}> {
    return this.loginCheckPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'token': string;
}>): {
'token': string;
} => r.body)
    );
  }

}
