/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import {
  apiGrowthPartnersGetCollection,
  ApiGrowthPartnersGetCollection$Params
} from '../fn/growth-partner/api-growth-partners-get-collection';
import { apiGrowthPartnersIdGet, ApiGrowthPartnersIdGet$Params } from '../fn/growth-partner/api-growth-partners-id-get';
import {
  apiGrowthPartnersIdPatch,
  ApiGrowthPartnersIdPatch$Params
} from '../fn/growth-partner/api-growth-partners-id-patch';
import { apiGrowthPartnersPost, ApiGrowthPartnersPost$Params } from '../fn/growth-partner/api-growth-partners-post';
import { ApiJsonldRead as GrowthPartnerApiJsonldRead } from '../models/GrowthPartner/api-jsonld-read';

@Injectable({ providedIn: 'root' })
export class ApiGrowthPartnerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiGrowthPartnersGetCollection()` */
  static readonly ApiGrowthPartnersGetCollectionPath = '/api/growth_partners';

  /**
   * Retrieves the collection of GrowthPartner resources.
   *
   * Retrieves the collection of GrowthPartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGrowthPartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGrowthPartnersGetCollection$Response(params?: ApiGrowthPartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiGrowthPartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of GrowthPartner resources.
   *
   * Retrieves the collection of GrowthPartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGrowthPartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGrowthPartnersGetCollection(params?: ApiGrowthPartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiGrowthPartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiGrowthPartnersPost()` */
  static readonly ApiGrowthPartnersPostPath = '/api/growth_partners';

  /**
   * Creates a GrowthPartner resource.
   *
   * Creates a GrowthPartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGrowthPartnersPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiGrowthPartnersPost$Response(params: ApiGrowthPartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<GrowthPartnerApiJsonldRead>> {
    return apiGrowthPartnersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a GrowthPartner resource.
   *
   * Creates a GrowthPartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGrowthPartnersPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiGrowthPartnersPost(params: ApiGrowthPartnersPost$Params, context?: HttpContext): Observable<GrowthPartnerApiJsonldRead> {
    return this.apiGrowthPartnersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<GrowthPartnerApiJsonldRead>): GrowthPartnerApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `apiGrowthPartnersIdGet()` */
  static readonly ApiGrowthPartnersIdGetPath = '/api/growth_partners/{id}';

  /**
   * Retrieves a GrowthPartner resource.
   *
   * Retrieves a GrowthPartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGrowthPartnersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGrowthPartnersIdGet$Response(params: ApiGrowthPartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<GrowthPartnerApiJsonldRead>> {
    return apiGrowthPartnersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a GrowthPartner resource.
   *
   * Retrieves a GrowthPartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGrowthPartnersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGrowthPartnersIdGet(params: ApiGrowthPartnersIdGet$Params, context?: HttpContext): Observable<GrowthPartnerApiJsonldRead> {
    return this.apiGrowthPartnersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<GrowthPartnerApiJsonldRead>): GrowthPartnerApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `apiGrowthPartnersIdPatch()` */
  static readonly ApiGrowthPartnersIdPatchPath = '/api/growth_partners/{id}';

  /**
   * Updates the GrowthPartner resource.
   *
   * Updates the GrowthPartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGrowthPartnersIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiGrowthPartnersIdPatch$Response(params: ApiGrowthPartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<GrowthPartnerApiJsonldRead>> {
    return apiGrowthPartnersIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the GrowthPartner resource.
   *
   * Updates the GrowthPartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGrowthPartnersIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiGrowthPartnersIdPatch(params: ApiGrowthPartnersIdPatch$Params, context?: HttpContext): Observable<GrowthPartnerApiJsonldRead> {
    return this.apiGrowthPartnersIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<GrowthPartnerApiJsonldRead>): GrowthPartnerApiJsonldRead => r.body)
    );
  }

}
