/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import {
  apiSolutionProvidersGetCollection,
  ApiSolutionProvidersGetCollection$Params
} from '../fn/solution-provider/api-solution-providers-get-collection';
import {
  apiSolutionProvidersIdGet,
  ApiSolutionProvidersIdGet$Params
} from '../fn/solution-provider/api-solution-providers-id-get';
import {
  apiSolutionProvidersIdPatch,
  ApiSolutionProvidersIdPatch$Params
} from '../fn/solution-provider/api-solution-providers-id-patch';
import {
  apiSolutionProvidersPost,
  ApiSolutionProvidersPost$Params
} from '../fn/solution-provider/api-solution-providers-post';
import {
  getSolutionProvidersByRegisteredPartner,
  GetSolutionProvidersByRegisteredPartner$Params
} from '../fn/solution-provider/get-solution-providers-by-registered-partner';
import { ApiJsonldRead as SolutionProviderApiJsonldRead } from '../models/SolutionProvider/api-jsonld-read';

@Injectable({ providedIn: 'root' })
export class ApiSolutionProviderService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSolutionProvidersGetCollection()` */
  static readonly ApiSolutionProvidersGetCollectionPath = '/api/solution_providers';

  /**
   * Retrieves the collection of SolutionProvider resources.
   *
   * Retrieves the collection of SolutionProvider resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionProvidersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionProvidersGetCollection$Response(params?: ApiSolutionProvidersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiSolutionProvidersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of SolutionProvider resources.
   *
   * Retrieves the collection of SolutionProvider resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionProvidersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionProvidersGetCollection(params?: ApiSolutionProvidersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiSolutionProvidersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiSolutionProvidersPost()` */
  static readonly ApiSolutionProvidersPostPath = '/api/solution_providers';

  /**
   * Creates a SolutionProvider resource.
   *
   * Creates a SolutionProvider resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionProvidersPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiSolutionProvidersPost$Response(params: ApiSolutionProvidersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionProviderApiJsonldRead>> {
    return apiSolutionProvidersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a SolutionProvider resource.
   *
   * Creates a SolutionProvider resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionProvidersPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiSolutionProvidersPost(params: ApiSolutionProvidersPost$Params, context?: HttpContext): Observable<SolutionProviderApiJsonldRead> {
    return this.apiSolutionProvidersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<SolutionProviderApiJsonldRead>): SolutionProviderApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `getSolutionProvidersByRegisteredPartner()` */
  static readonly GetSolutionProvidersByRegisteredPartnerPath = '/api/solution_providers/by_registered_partner/{registeredPartnerId}';

  /**
   * Retrieves the collection of SolutionProvider resources.
   *
   * Retrieves the collection of SolutionProvider resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSolutionProvidersByRegisteredPartner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSolutionProvidersByRegisteredPartner$Response(params: GetSolutionProvidersByRegisteredPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return getSolutionProvidersByRegisteredPartner(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of SolutionProvider resources.
   *
   * Retrieves the collection of SolutionProvider resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSolutionProvidersByRegisteredPartner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSolutionProvidersByRegisteredPartner(params: GetSolutionProvidersByRegisteredPartner$Params, context?: HttpContext): Observable<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.getSolutionProvidersByRegisteredPartner$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiSolutionProvidersIdGet()` */
  static readonly ApiSolutionProvidersIdGetPath = '/api/solution_providers/{id}';

  /**
   * Retrieves a SolutionProvider resource.
   *
   * Retrieves a SolutionProvider resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionProvidersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionProvidersIdGet$Response(params: ApiSolutionProvidersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionProviderApiJsonldRead>> {
    return apiSolutionProvidersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a SolutionProvider resource.
   *
   * Retrieves a SolutionProvider resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionProvidersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionProvidersIdGet(params: ApiSolutionProvidersIdGet$Params, context?: HttpContext): Observable<SolutionProviderApiJsonldRead> {
    return this.apiSolutionProvidersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<SolutionProviderApiJsonldRead>): SolutionProviderApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `apiSolutionProvidersIdPatch()` */
  static readonly ApiSolutionProvidersIdPatchPath = '/api/solution_providers/{id}';

  /**
   * Updates the SolutionProvider resource.
   *
   * Updates the SolutionProvider resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionProvidersIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiSolutionProvidersIdPatch$Response(params: ApiSolutionProvidersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<SolutionProviderApiJsonldRead>> {
    return apiSolutionProvidersIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the SolutionProvider resource.
   *
   * Updates the SolutionProvider resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionProvidersIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiSolutionProvidersIdPatch(params: ApiSolutionProvidersIdPatch$Params, context?: HttpContext): Observable<SolutionProviderApiJsonldRead> {
    return this.apiSolutionProvidersIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<SolutionProviderApiJsonldRead>): SolutionProviderApiJsonldRead => r.body)
    );
  }

}
