/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiUsersGetCollection, ApiUsersGetCollection$Params } from '../fn/user/api-users-get-collection';
import { apiUsersIdGet, ApiUsersIdGet$Params } from '../fn/user/api-users-id-get';
import { apiUsersIdPatch, ApiUsersIdPatch$Params } from '../fn/user/api-users-id-patch';
import { apiUsersPost, ApiUsersPost$Params } from '../fn/user/api-users-post';
import {
  getUsersByRegisteredPartner,
  GetUsersByRegisteredPartner$Params
} from '../fn/user/get-users-by-registered-partner';
import { ApiJsonld as UserApiJsonld } from '../models/User/api-jsonld';

@Injectable({ providedIn: 'root' })
export class ApiUserService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiUsersGetCollection()` */
  static readonly ApiUsersGetCollectionPath = '/api/users';

  /**
   * Retrieves the collection of User resources.
   *
   * Retrieves the collection of User resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersGetCollection$Response(params?: ApiUsersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiUsersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of User resources.
   *
   * Retrieves the collection of User resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersGetCollection(params?: ApiUsersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiUsersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiUsersPost()` */
  static readonly ApiUsersPostPath = '/api/users';

  /**
   * Creates a User resource.
   *
   * Creates a User resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiUsersPost$Response(params: ApiUsersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiJsonld>> {
    return apiUsersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a User resource.
   *
   * Creates a User resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiUsersPost(params: ApiUsersPost$Params, context?: HttpContext): Observable<UserApiJsonld> {
    return this.apiUsersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserApiJsonld>): UserApiJsonld => r.body)
    );
  }

  /** Path part for operation `getUsersByRegisteredPartner()` */
  static readonly GetUsersByRegisteredPartnerPath = '/api/users/by_registered_partner/{registeredPartnerId}';

  /**
   * Retrieves the collection of User resources.
   *
   * Retrieves the collection of User resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUsersByRegisteredPartner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByRegisteredPartner$Response(params: GetUsersByRegisteredPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return getUsersByRegisteredPartner(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of User resources.
   *
   * Retrieves the collection of User resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUsersByRegisteredPartner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUsersByRegisteredPartner(params: GetUsersByRegisteredPartner$Params, context?: HttpContext): Observable<{
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.getUsersByRegisteredPartner$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<UserApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiUsersIdGet()` */
  static readonly ApiUsersIdGetPath = '/api/users/{id}';

  /**
   * Retrieves a User resource.
   *
   * Retrieves a User resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersIdGet$Response(params: ApiUsersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiJsonld>> {
    return apiUsersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a User resource.
   *
   * Retrieves a User resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiUsersIdGet(params: ApiUsersIdGet$Params, context?: HttpContext): Observable<UserApiJsonld> {
    return this.apiUsersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserApiJsonld>): UserApiJsonld => r.body)
    );
  }

  /** Path part for operation `apiUsersIdPatch()` */
  static readonly ApiUsersIdPatchPath = '/api/users/{id}';

  /**
   * Updates the User resource.
   *
   * Updates the User resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiUsersIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiUsersIdPatch$Response(params: ApiUsersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<UserApiJsonld>> {
    return apiUsersIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the User resource.
   *
   * Updates the User resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiUsersIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiUsersIdPatch(params: ApiUsersIdPatch$Params, context?: HttpContext): Observable<UserApiJsonld> {
    return this.apiUsersIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserApiJsonld>): UserApiJsonld => r.body)
    );
  }

}
