/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiClientsGetCollection, ApiClientsGetCollection$Params } from '../fn/client/api-clients-get-collection';
import { apiClientsIdGet, ApiClientsIdGet$Params } from '../fn/client/api-clients-id-get';
import { apiClientsIdPatch, ApiClientsIdPatch$Params } from '../fn/client/api-clients-id-patch';
import {
  apiClientsIdregisteredPartnerPatch,
  ApiClientsIdregisteredPartnerPatch$Params
} from '../fn/client/api-clients-idregistered-partner-patch';
import { apiClientsPost, ApiClientsPost$Params } from '../fn/client/api-clients-post';
import { ApiRead as ClientJsonldClientApiRead } from '../models/Client/jsonld-client/api-read';
import {
  getClientsByRegisteredPartner,
  GetClientsByRegisteredPartner$Params
} from '../fn/client/get-clients-by-registered-partner';

@Injectable({ providedIn: 'root' })
export class ApiClientService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiClientsGetCollection()` */
  static readonly ApiClientsGetCollectionPath = '/api/clients';

  /**
   * Retrieves the collection of Client resources.
   *
   * Retrieves the collection of Client resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientsGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientsGetCollection$Response(params?: ApiClientsGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiClientsGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of Client resources.
   *
   * Retrieves the collection of Client resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientsGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientsGetCollection(params?: ApiClientsGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiClientsGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiClientsPost()` */
  static readonly ApiClientsPostPath = '/api/clients';

  /**
   * Creates a Client resource.
   *
   * Creates a Client resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientsPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiClientsPost$Response(params: ApiClientsPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
    return apiClientsPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a Client resource.
   *
   * Creates a Client resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientsPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiClientsPost(params: ApiClientsPost$Params, context?: HttpContext): Observable<ClientJsonldClientApiRead> {
    return this.apiClientsPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientJsonldClientApiRead>): ClientJsonldClientApiRead => r.body)
    );
  }

  /** Path part for operation `getClientsByRegisteredPartner()` */
  static readonly GetClientsByRegisteredPartnerPath = '/api/clients/by_registered_partner/{registeredPartnerId}';

  /**
   * Retrieves the collection of Client resources.
   *
   * Retrieves the collection of Client resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getClientsByRegisteredPartner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getClientsByRegisteredPartner$Response(params: GetClientsByRegisteredPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return getClientsByRegisteredPartner(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of Client resources.
   *
   * Retrieves the collection of Client resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getClientsByRegisteredPartner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getClientsByRegisteredPartner(params: GetClientsByRegisteredPartner$Params, context?: HttpContext): Observable<{
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.getClientsByRegisteredPartner$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<ClientJsonldClientApiRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiClientsIdGet()` */
  static readonly ApiClientsIdGetPath = '/api/clients/{id}';

  /**
   * Retrieves a Client resource.
   *
   * Retrieves a Client resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientsIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientsIdGet$Response(params: ApiClientsIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
    return apiClientsIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a Client resource.
   *
   * Retrieves a Client resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientsIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiClientsIdGet(params: ApiClientsIdGet$Params, context?: HttpContext): Observable<ClientJsonldClientApiRead> {
    return this.apiClientsIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientJsonldClientApiRead>): ClientJsonldClientApiRead => r.body)
    );
  }

  /** Path part for operation `apiClientsIdPatch()` */
  static readonly ApiClientsIdPatchPath = '/api/clients/{id}';

  /**
   * Updates the Client resource.
   *
   * Updates the Client resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientsIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiClientsIdPatch$Response(params: ApiClientsIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
    return apiClientsIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the Client resource.
   *
   * Updates the Client resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientsIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiClientsIdPatch(params: ApiClientsIdPatch$Params, context?: HttpContext): Observable<ClientJsonldClientApiRead> {
    return this.apiClientsIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientJsonldClientApiRead>): ClientJsonldClientApiRead => r.body)
    );
  }

  /** Path part for operation `apiClientsIdregisteredPartnerPatch()` */
  static readonly ApiClientsIdregisteredPartnerPatchPath = '/api/clients/{id}/registeredPartner';

  /**
   * Updates the Client resource.
   *
   * Updates the Client resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiClientsIdregisteredPartnerPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiClientsIdregisteredPartnerPatch$Response(params: ApiClientsIdregisteredPartnerPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientJsonldClientApiRead>> {
    return apiClientsIdregisteredPartnerPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the Client resource.
   *
   * Updates the Client resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiClientsIdregisteredPartnerPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiClientsIdregisteredPartnerPatch(params: ApiClientsIdregisteredPartnerPatch$Params, context?: HttpContext): Observable<ClientJsonldClientApiRead> {
    return this.apiClientsIdregisteredPartnerPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<ClientJsonldClientApiRead>): ClientJsonldClientApiRead => r.body)
    );
  }

}
