/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from '../models/AffiliatePartner/api-jsonld-read';
import {
  apiAffiliatePartnersGetCollection,
  ApiAffiliatePartnersGetCollection$Params
} from '../fn/affiliate-partner/api-affiliate-partners-get-collection';
import {
  apiGrowthPartnersGetCollection,
  ApiGrowthPartnersGetCollection$Params
} from '../fn/growth-partner/api-growth-partners-get-collection';
import { apiPartnersGetCollection, ApiPartnersGetCollection$Params } from '../fn/partner/api-partners-get-collection';
import { apiPartnersIdDelete, ApiPartnersIdDelete$Params } from '../fn/partner/api-partners-id-delete';
import { apiPartnersIdGet, ApiPartnersIdGet$Params } from '../fn/partner/api-partners-id-get';
import { apiPartnersIdPatch, ApiPartnersIdPatch$Params } from '../fn/partner/api-partners-id-patch';
import { apiPartnersPost, ApiPartnersPost$Params } from '../fn/partner/api-partners-post';
import {
  apiSolutionPartnersGetCollection,
  ApiSolutionPartnersGetCollection$Params
} from '../fn/solution-partner/api-solution-partners-get-collection';
import {
  apiSolutionProvidersGetCollection,
  ApiSolutionProvidersGetCollection$Params
} from '../fn/solution-provider/api-solution-providers-get-collection';
import { ApiJsonldRead as GrowthPartnerApiJsonldRead } from '../models/GrowthPartner/api-jsonld-read';
import { ApiJsonld as PartnerApiJsonld } from '../models/Partner/api-jsonld';
import { ApiJsonldRead as SolutionPartnerApiJsonldRead } from '../models/SolutionPartner/api-jsonld-read';
import { ApiJsonldRead as SolutionProviderApiJsonldRead } from '../models/SolutionProvider/api-jsonld-read';

@Injectable({ providedIn: 'root' })
export class ApiPartnerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAffiliatePartnersGetCollection()` */
  static readonly ApiAffiliatePartnersGetCollectionPath = '/api/affiliate_partners';

  /**
   * Retrieves the collection of AffiliatePartner resources.
   *
   * Retrieves the collection of AffiliatePartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAffiliatePartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAffiliatePartnersGetCollection$Response(params?: ApiAffiliatePartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiAffiliatePartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of AffiliatePartner resources.
   *
   * Retrieves the collection of AffiliatePartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAffiliatePartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAffiliatePartnersGetCollection(params?: ApiAffiliatePartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiAffiliatePartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiGrowthPartnersGetCollection()` */
  static readonly ApiGrowthPartnersGetCollectionPath = '/api/growth_partners';

  /**
   * Retrieves the collection of GrowthPartner resources.
   *
   * Retrieves the collection of GrowthPartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGrowthPartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGrowthPartnersGetCollection$Response(params?: ApiGrowthPartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiGrowthPartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of GrowthPartner resources.
   *
   * Retrieves the collection of GrowthPartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGrowthPartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGrowthPartnersGetCollection(params?: ApiGrowthPartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiGrowthPartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<GrowthPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiPartnersGetCollection()` */
  static readonly ApiPartnersGetCollectionPath = '/api/partners';

  /**
   * Retrieves the collection of Partner resources.
   *
   * Retrieves the collection of Partner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPartnersGetCollection$Response(params?: ApiPartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<PartnerApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiPartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of Partner resources.
   *
   * Retrieves the collection of Partner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPartnersGetCollection(params?: ApiPartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<PartnerApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiPartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<PartnerApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<PartnerApiJsonld>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiPartnersPost()` */
  static readonly ApiPartnersPostPath = '/api/partners';

  /**
   * Creates a Partner resource.
   *
   * Creates a Partner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPartnersPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiPartnersPost$Response(params: ApiPartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApiJsonld>> {
    return apiPartnersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a Partner resource.
   *
   * Creates a Partner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPartnersPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiPartnersPost(params: ApiPartnersPost$Params, context?: HttpContext): Observable<PartnerApiJsonld> {
    return this.apiPartnersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<PartnerApiJsonld>): PartnerApiJsonld => r.body)
    );
  }

  /** Path part for operation `apiPartnersIdGet()` */
  static readonly ApiPartnersIdGetPath = '/api/partners/{id}';

  /**
   * Retrieves a Partner resource.
   *
   * Retrieves a Partner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPartnersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPartnersIdGet$Response(params: ApiPartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApiJsonld>> {
    return apiPartnersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a Partner resource.
   *
   * Retrieves a Partner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPartnersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPartnersIdGet(params: ApiPartnersIdGet$Params, context?: HttpContext): Observable<PartnerApiJsonld> {
    return this.apiPartnersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<PartnerApiJsonld>): PartnerApiJsonld => r.body)
    );
  }

  /** Path part for operation `apiPartnersIdDelete()` */
  static readonly ApiPartnersIdDeletePath = '/api/partners/{id}';

  /**
   * Removes the Partner resource.
   *
   * Removes the Partner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPartnersIdDelete()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPartnersIdDelete$Response(params: ApiPartnersIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiPartnersIdDelete(this.http, this.rootUrl, params, context);
  }

  /**
   * Removes the Partner resource.
   *
   * Removes the Partner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPartnersIdDelete$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiPartnersIdDelete(params: ApiPartnersIdDelete$Params, context?: HttpContext): Observable<void> {
    return this.apiPartnersIdDelete$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiPartnersIdPatch()` */
  static readonly ApiPartnersIdPatchPath = '/api/partners/{id}';

  /**
   * Updates the Partner resource.
   *
   * Updates the Partner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiPartnersIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiPartnersIdPatch$Response(params: ApiPartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApiJsonld>> {
    return apiPartnersIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the Partner resource.
   *
   * Updates the Partner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiPartnersIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiPartnersIdPatch(params: ApiPartnersIdPatch$Params, context?: HttpContext): Observable<PartnerApiJsonld> {
    return this.apiPartnersIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<PartnerApiJsonld>): PartnerApiJsonld => r.body)
    );
  }

  /** Path part for operation `apiSolutionPartnersGetCollection()` */
  static readonly ApiSolutionPartnersGetCollectionPath = '/api/solution_partners';

  /**
   * Retrieves the collection of SolutionPartner resources.
   *
   * Retrieves the collection of SolutionPartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionPartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionPartnersGetCollection$Response(params?: ApiSolutionPartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiSolutionPartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of SolutionPartner resources.
   *
   * Retrieves the collection of SolutionPartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionPartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionPartnersGetCollection(params?: ApiSolutionPartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiSolutionPartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<SolutionPartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiSolutionProvidersGetCollection()` */
  static readonly ApiSolutionProvidersGetCollectionPath = '/api/solution_providers';

  /**
   * Retrieves the collection of SolutionProvider resources.
   *
   * Retrieves the collection of SolutionProvider resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSolutionProvidersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionProvidersGetCollection$Response(params?: ApiSolutionProvidersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiSolutionProvidersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of SolutionProvider resources.
   *
   * Retrieves the collection of SolutionProvider resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSolutionProvidersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSolutionProvidersGetCollection(params?: ApiSolutionProvidersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiSolutionProvidersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<SolutionProviderApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

}
