/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiJsonldRead as AffiliatePartnerApiJsonldRead } from '../models/AffiliatePartner/api-jsonld-read';
import {
  apiAffiliatePartnersGetCollection,
  ApiAffiliatePartnersGetCollection$Params
} from '../fn/affiliate-partner/api-affiliate-partners-get-collection';
import {
  apiAffiliatePartnersIdGet,
  ApiAffiliatePartnersIdGet$Params
} from '../fn/affiliate-partner/api-affiliate-partners-id-get';
import {
  apiAffiliatePartnersIdPatch,
  ApiAffiliatePartnersIdPatch$Params
} from '../fn/affiliate-partner/api-affiliate-partners-id-patch';
import {
  apiAffiliatePartnersPost,
  ApiAffiliatePartnersPost$Params
} from '../fn/affiliate-partner/api-affiliate-partners-post';
import {
  getAffiliatePartnersByRegisteredPartner,
  GetAffiliatePartnersByRegisteredPartner$Params
} from '../fn/affiliate-partner/get-affiliate-partners-by-registered-partner';

@Injectable({ providedIn: 'root' })
export class ApiAffiliatePartnerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAffiliatePartnersGetCollection()` */
  static readonly ApiAffiliatePartnersGetCollectionPath = '/api/affiliate_partners';

  /**
   * Retrieves the collection of AffiliatePartner resources.
   *
   * Retrieves the collection of AffiliatePartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAffiliatePartnersGetCollection()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAffiliatePartnersGetCollection$Response(params?: ApiAffiliatePartnersGetCollection$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return apiAffiliatePartnersGetCollection(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of AffiliatePartner resources.
   *
   * Retrieves the collection of AffiliatePartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAffiliatePartnersGetCollection$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAffiliatePartnersGetCollection(params?: ApiAffiliatePartnersGetCollection$Params, context?: HttpContext): Observable<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.apiAffiliatePartnersGetCollection$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiAffiliatePartnersPost()` */
  static readonly ApiAffiliatePartnersPostPath = '/api/affiliate_partners';

  /**
   * Creates a AffiliatePartner resource.
   *
   * Creates a AffiliatePartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAffiliatePartnersPost()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiAffiliatePartnersPost$Response(params: ApiAffiliatePartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<AffiliatePartnerApiJsonldRead>> {
    return apiAffiliatePartnersPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a AffiliatePartner resource.
   *
   * Creates a AffiliatePartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAffiliatePartnersPost$Response()` instead.
   *
   * This method sends `application/ld+json` and handles request body of type `application/ld+json`.
   */
  apiAffiliatePartnersPost(params: ApiAffiliatePartnersPost$Params, context?: HttpContext): Observable<AffiliatePartnerApiJsonldRead> {
    return this.apiAffiliatePartnersPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<AffiliatePartnerApiJsonldRead>): AffiliatePartnerApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `getAffiliatePartnersByRegisteredPartner()` */
  static readonly GetAffiliatePartnersByRegisteredPartnerPath = '/api/affiliate_partners/by_registered_partner/{registeredPartnerId}';

  /**
   * Retrieves the collection of AffiliatePartner resources.
   *
   * Retrieves the collection of AffiliatePartner resources.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAffiliatePartnersByRegisteredPartner()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAffiliatePartnersByRegisteredPartner$Response(params: GetAffiliatePartnersByRegisteredPartner$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>> {
    return getAffiliatePartnersByRegisteredPartner(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves the collection of AffiliatePartner resources.
   *
   * Retrieves the collection of AffiliatePartner resources.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAffiliatePartnersByRegisteredPartner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAffiliatePartnersByRegisteredPartner(params: GetAffiliatePartnersByRegisteredPartner$Params, context?: HttpContext): Observable<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}> {
    return this.getAffiliatePartnersByRegisteredPartner$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
}>): {
'member': Array<AffiliatePartnerApiJsonldRead>;
'totalItems'?: number;
'view'?: {
'@id'?: string;
'@type'?: string;
'first'?: string;
'last'?: string;
'previous'?: string;
'next'?: string;
};
'search'?: {
'@type'?: string;
'template'?: string;
'variableRepresentation'?: string;
'mapping'?: Array<{
'@type'?: string;
'variable'?: string;
'property'?: string;
'required'?: boolean;
}>;
};
} => r.body)
    );
  }

  /** Path part for operation `apiAffiliatePartnersIdGet()` */
  static readonly ApiAffiliatePartnersIdGetPath = '/api/affiliate_partners/{id}';

  /**
   * Retrieves a AffiliatePartner resource.
   *
   * Retrieves a AffiliatePartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAffiliatePartnersIdGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAffiliatePartnersIdGet$Response(params: ApiAffiliatePartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<AffiliatePartnerApiJsonldRead>> {
    return apiAffiliatePartnersIdGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieves a AffiliatePartner resource.
   *
   * Retrieves a AffiliatePartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAffiliatePartnersIdGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAffiliatePartnersIdGet(params: ApiAffiliatePartnersIdGet$Params, context?: HttpContext): Observable<AffiliatePartnerApiJsonldRead> {
    return this.apiAffiliatePartnersIdGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<AffiliatePartnerApiJsonldRead>): AffiliatePartnerApiJsonldRead => r.body)
    );
  }

  /** Path part for operation `apiAffiliatePartnersIdPatch()` */
  static readonly ApiAffiliatePartnersIdPatchPath = '/api/affiliate_partners/{id}';

  /**
   * Updates the AffiliatePartner resource.
   *
   * Updates the AffiliatePartner resource.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAffiliatePartnersIdPatch()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiAffiliatePartnersIdPatch$Response(params: ApiAffiliatePartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<AffiliatePartnerApiJsonldRead>> {
    return apiAffiliatePartnersIdPatch(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates the AffiliatePartner resource.
   *
   * Updates the AffiliatePartner resource.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAffiliatePartnersIdPatch$Response()` instead.
   *
   * This method sends `application/merge-patch+json` and handles request body of type `application/merge-patch+json`.
   */
  apiAffiliatePartnersIdPatch(params: ApiAffiliatePartnersIdPatch$Params, context?: HttpContext): Observable<AffiliatePartnerApiJsonldRead> {
    return this.apiAffiliatePartnersIdPatch$Response(params, context).pipe(
      map((r: StrictHttpResponse<AffiliatePartnerApiJsonldRead>): AffiliatePartnerApiJsonldRead => r.body)
    );
  }

}
