/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiPost {
  email?: string;
  name?: string;
  partner?: string;
  isActive?: boolean;
}
