/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiPartner } from '../../models/api-partner';
import { ApiJsonld as PartnerApiJsonld } from '../../models/Partner/api-jsonld';

export interface ApiPartnersIdPatch$Params {

/**
 * Partner identifier
 */
  id: string;
  
    /**
     * The updated Partner resource
     */
    body: ApiPartner
}

export function apiPartnersIdPatch(http: HttpClient, rootUrl: string, params: ApiPartnersIdPatch$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApiJsonld>> {
  const rb = new RequestBuilder(rootUrl, apiPartnersIdPatch.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
    rb.body(params.body, 'application/merge-patch+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartnerApiJsonld>;
    })
  );
}

apiPartnersIdPatch.PATH = '/api/partners/{id}';
