/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonld as PartnerApiJsonld } from '../../models/Partner/api-jsonld';

export interface ApiPartnersPost$Params {
  
    /**
     * The new Partner resource
     */
    body: PartnerApiJsonld
}

export function apiPartnersPost(http: HttpClient, rootUrl: string, params: ApiPartnersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApiJsonld>> {
  const rb = new RequestBuilder(rootUrl, apiPartnersPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/ld+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartnerApiJsonld>;
    })
  );
}

apiPartnersPost.PATH = '/api/partners';
