/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiJsonld as PartnerApiJsonld } from '../../models/Partner/api-jsonld';

export interface ApiPartnersIdGet$Params {

/**
 * Partner identifier
 */
  id: string;
}

export function apiPartnersIdGet(http: HttpClient, rootUrl: string, params: ApiPartnersIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<PartnerApiJsonld>> {
  const rb = new RequestBuilder(rootUrl, apiPartnersIdGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {"style":"simple","explode":false});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/ld+json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PartnerApiJsonld>;
    })
  );
}

apiPartnersIdGet.PATH = '/api/partners/{id}';
